name: Node.js CI

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    - run: yarn
    - uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}
    - run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Actions"
    - run: yarn deploy
      env:
        GIT_USER: giltho
        USE_SSH: true
        
